<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDuZPgcW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDuZPgcW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDuZPgcW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDuZPgcW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDuZPgcW\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'DuZPgcW',
    'container.build_id' => '355a42ac',
    'container.build_time' => 1548072106,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDuZPgcW');
